---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: applications
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: chineduezeigbo/scalable-capital:latest
        resources:
          requests:
            cpu: "125m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "125m"
        ports:
        - containerPort: 8990


---

apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: applications
  labels:
    app: app1
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
  - port: 7101
    targetPort: 8990

        
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: scalable-hpa
  namespace: applications
  labels:
    app: app1
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app1
  targetCPUUtilizationPercentage: 90

