apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: applications
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: chineduezeigbo/scalable-capital:latest
        resources:
          requests:
            cpu: "125m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 8990