---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: chineduezeigbo/scalable-capital:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "125m"
        ports:
        - containerPort: 8990

---

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
  - port: 7101
    targetPort: 8990
